name = "tutorial"
uuid = "cee32004-52e6-43b9-a8bb-d89c6402ab1a"
authors = ["Danylo Malyuta <12475811+dmalyuta@users.noreply.github.com>"]
version = "0.1.0"

[compat]
julia = "=1.7.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SCPToolbox = "bd2bc758-a5dc-11eb-050f-6b2434548817"
